---
title: "multiscale_psy"
author: "Adam"
date: "7/8/2021"
output: html_document
---

```{r}
#libraries
library(lmtest)
library(gratia)
library(ggplot2)
library(reshape2)
library(dplyr)
library(ggpubr)
library(vroom)
library(data.table)
library(mgcv)
library(ppcor)
library(viridis)
library(pammtools)
# Functions for age effect calculations. Because of the complications introduced by modeling age as a combination of basis functions (spline), the rest of the markdown will heavily lean on these functions to analyze effect size and statistical significance of non-linear age effects.

# First for effect size, we take the difference in adjusted R^2 between a model that includes an age term and a model that does not - essentially, we are using two models to estimate the variance in subject-level data explained by age. To derive the directionality of this effect, we fit a linear model (partial correlation) and match the sign of the age effect (+ or -) to the size of the age effect(delta adjusted R^2). In this case, the directionality tells us whether FC tends to goes up or down with age.

# OVERALL
# FEAR
# ANX-MIS
# PSYCHOSIS
# EXTERN

DeltaR2EstVec_OV<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(masterdf$overall_psychopathology_4factorv2),as.numeric(masterdf$Age),as.numeric(masterdf$Sex),masterdf$Motion,x))
  colnames(scaledf)<-c('overall_psychopathology_4factorv2','Age','Sex','Motion','varofint')
  
  # no-Td model (b.w. ~ sex + motion)
  noTdGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  noTdSum<-summary(noTdGam)
  # Td-included model for measuring difference
  TdGam<-gam(varofint~overall_psychopathology_4factorv2+Sex+Motion+s(Age,k=3),data=scaledf)
  TdSum<-summary(TdGam)
  
  dif<-TdSum$r.sq-noTdSum$r.sq
  
  # partial spearmans to extract EF relation (for direction)
  pspear=pcor(scaledf,method='spearman')$estimate
  corest<-pspear[5]
  if(corest<0){
    dif=dif*-1
  }
  
  return(dif)

}

# Next, to derive the statistical significance of observed age effects, we need to test if the two models (one with an age term, one without) are significantly different. We use an ANOVA for this procedure. These p-values will eventually be FDR-corrected.

# chisq test sig. output
DeltaPEstVec_OV<-function(x){
  
    # relevant df
  scaledf<-data.frame(cbind(as.numeric(masterdf$overall_psychopathology_4factorv2),as.numeric(masterdf$Age),as.numeric(masterdf$Sex),masterdf$Motion,x))
  colnames(scaledf)<-c('overall_psychopathology_4factorv2','Age','Sex','Motion','varofint')
  
  # no-EF model (segreg ~ sex + motion)
  noTdGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  # EF-included model for measuring difference
  TdGam<-gam(varofint~overall_psychopathology_4factorv2+Sex+Motion+s(Age,k=3),data=scaledf)
  
  # test of dif with anova.gam
  anovaRes<-anova.gam(noTdGam,TdGam,test='Chisq')
  anovaP<-anovaRes$`Pr(>Chi)`
  anovaP2<-unlist(anovaP)
  return(anovaP2[2])
}


# difference in R2
DeltaR2EstVec_FE<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(masterdf$phobias_4factorv2),as.numeric(masterdf$Age),as.numeric(masterdf$Sex),masterdf$Motion,x))
  colnames(scaledf)<-c('phobias_4factorv2','Age','Sex','Motion','varofint')
  
  # no-Td model (b.w. ~ sex + motion)
  noTdGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  noTdSum<-summary(noTdGam)
  # Td-included model for measuring difference
  TdGam<-gam(varofint~phobias_4factorv2+Sex+Motion+s(Age,k=3),data=scaledf)
  TdSum<-summary(TdGam)
  
  dif<-TdSum$r.sq-noTdSum$r.sq
  
  # partial spearmans to extract EF relation (for direction)
  pspear=pcor(scaledf,method='spearman')$estimate
  corest<-pspear[5]
  if(corest<0){
    dif=dif*-1
  }
  
  return(dif)

}

# chisq test sig. output
DeltaPEstVec_FE<-function(x){
  
    # relevant df
  scaledf<-data.frame(cbind(as.numeric(masterdf$phobias_4factorv2),as.numeric(masterdf$Age),as.numeric(masterdf$Sex),masterdf$Motion,x))
  colnames(scaledf)<-c('phobias_4factorv2','Age','Sex','Motion','varofint')
  
  # no-EF model (segreg ~ sex + motion)
  noTdGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  # EF-included model for measuring difference
  TdGam<-gam(varofint~phobias_4factorv2+Sex+Motion+s(Age,k=3),data=scaledf)
  
  # test of dif with anova.gam
  anovaRes<-anova.gam(noTdGam,TdGam,test='Chisq')
  anovaP<-anovaRes$`Pr(>Chi)`
  anovaP2<-unlist(anovaP)
  return(anovaP2[2])

}
DeltaR2EstVec_AM<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(masterdf$mood_4factorv2),as.numeric(masterdf$Age),as.numeric(masterdf$Sex),masterdf$Motion,x))
  colnames(scaledf)<-c('mood_4factorv2','Age','Sex','Motion','varofint')
  
  # no-Td model (b.w. ~ sex + motion)
  noTdGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  noTdSum<-summary(noTdGam)
  # Td-included model for measuring difference
  TdGam<-gam(varofint~mood_4factorv2+Sex+Motion+s(Age,k=3),data=scaledf)
  TdSum<-summary(TdGam)
  
  dif<-TdSum$r.sq-noTdSum$r.sq
  
  # partial spearmans to extract EF relation (for direction)
  pspear=pcor(scaledf,method='spearman')$estimate
  corest<-pspear[5]
  if(corest<0){
    dif=dif*-1
  }
  
  return(dif)

}

# chisq test sig. output
DeltaPEstVec_AM<-function(x){
  
    # relevant df
  scaledf<-data.frame(cbind(as.numeric(masterdf$mood_4factorv2),as.numeric(masterdf$Age),as.numeric(masterdf$Sex),masterdf$Motion,x))
  colnames(scaledf)<-c('mood_4factorv2','Age','Sex','Motion','varofint')
  
  # no-EF model (segreg ~ sex + motion)
  noTdGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  # EF-included model for measuring difference
  TdGam<-gam(varofint~mood_4factorv2+Sex+Motion+s(Age,k=3),data=scaledf)
  
  # test of dif with anova.gam
  anovaRes<-anova.gam(noTdGam,TdGam,test='Chisq')
  anovaP<-anovaRes$`Pr(>Chi)`
  anovaP2<-unlist(anovaP)
  return(anovaP2[2])

}
# Next, to derive the statistical significance of observed age effects, we need to test if the two models (one with an age term, one without) are significantly different. We use an ANOVA for this procedure. These p-values will eventually be FDR-corrected.

# chisq test sig. output
DeltaR2EstVec_PS<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(masterdf$psychosis_4factorv2),as.numeric(masterdf$Age),as.numeric(masterdf$Sex),masterdf$Motion,x))
  colnames(scaledf)<-c('psychosis_4factorv2','Age','Sex','Motion','varofint')
  
  # no-Td model (b.w. ~ sex + motion)
  noTdGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  noTdSum<-summary(noTdGam)
  # Td-included model for measuring difference
  TdGam<-gam(varofint~psychosis_4factorv2+Sex+Motion+s(Age,k=3),data=scaledf)
  TdSum<-summary(TdGam)
  
  dif<-TdSum$r.sq-noTdSum$r.sq
  
  # partial spearmans to extract EF relation (for direction)
  pspear=pcor(scaledf,method='spearman')$estimate
  corest<-pspear[5]
  if(corest<0){
    dif=dif*-1
  }
  
  return(dif)

}

# Next, to derive the statistical significance of observed age effects, we need to test if the two models (one with an age term, one without) are significantly different. We use an ANOVA for this procedure. These p-values will eventually be FDR-corrected.

# chisq test sig. output
DeltaPEstVec_PS<-function(x){
  
    # relevant df
  scaledf<-data.frame(cbind(as.numeric(masterdf$psychosis_4factorv2),as.numeric(masterdf$Age),as.numeric(masterdf$Sex),masterdf$Motion,x))
  colnames(scaledf)<-c('psychosis_4factorv2','Age','Sex','Motion','varofint')
  
  # no-EF model (segreg ~ sex + motion)
  noTdGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  # EF-included model for measuring difference
  TdGam<-gam(varofint~psychosis_4factorv2+Sex+Motion+s(Age,k=3),data=scaledf)
  
  # test of dif with anova.gam
  anovaRes<-anova.gam(noTdGam,TdGam,test='Chisq')
  anovaP<-anovaRes$`Pr(>Chi)`
  anovaP2<-unlist(anovaP)
  return(anovaP2[2])
}

DeltaR2EstVec_EX<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(masterdf$externalizing_4factorv2),as.numeric(masterdf$Age),as.numeric(masterdf$Sex),masterdf$Motion,x))
  colnames(scaledf)<-c('externalizing_4factorv2','Age','Sex','Motion','varofint')
  
  # no-Td model (b.w. ~ sex + motion)
  noTdGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  noTdSum<-summary(noTdGam)
  # Td-included model for measuring difference
  TdGam<-gam(varofint~externalizing_4factorv2+Sex+Motion+s(Age,k=3),data=scaledf)
  TdSum<-summary(TdGam)
  
  dif<-TdSum$r.sq-noTdSum$r.sq
  
  # partial spearmans to extract EF relation (for direction)
  pspear=pcor(scaledf,method='spearman')$estimate
  corest<-pspear[5]
  if(corest<0){
    dif=dif*-1
  }
  
  return(dif)

}

# Next, to derive the statistical significance of observed age effects, we need to test if the two models (one with an age term, one without) are significantly different. We use an ANOVA for this procedure. These p-values will eventually be FDR-corrected.

# chisq test sig. output
DeltaPEstVec_EX<-function(x){
  
    # relevant df
  scaledf<-data.frame(cbind(as.numeric(masterdf$externalizing_4factorv2),as.numeric(masterdf$Age),as.numeric(masterdf$Sex),masterdf$Motion,x))
  colnames(scaledf)<-c('externalizing_4factorv2','Age','Sex','Motion','varofint')
  
  # no-EF model (segreg ~ sex + motion)
  noTdGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  # EF-included model for measuring difference
  TdGam<-gam(varofint~externalizing_4factorv2+Sex+Motion+s(Age,k=3),data=scaledf)
  
  # test of dif with anova.gam
  anovaRes<-anova.gam(noTdGam,TdGam,test='Chisq')
  anovaP<-anovaRes$`Pr(>Chi)`
  anovaP2<-unlist(anovaP)
  return(anovaP2[2])
}

```
```{r}
# more functions
DeltaR2EstVec_OV_s<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(masterdf_sub$overall_psychopathology_4factorv2),as.numeric(masterdf_sub$Age),as.numeric(masterdf_sub$Sex),masterdf_sub$Motion,x))
  colnames(scaledf)<-c('overall_psychopathology_4factorv2','Age','Sex','Motion','varofint')
  
  # no-Td model (b.w. ~ sex + motion)
  noTdGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  noTdSum<-summary(noTdGam)
  # Td-included model for measuring difference
  TdGam<-gam(varofint~overall_psychopathology_4factorv2+Sex+Motion+s(Age,k=3),data=scaledf)
  TdSum<-summary(TdGam)
  
  dif<-TdSum$r.sq-noTdSum$r.sq
  
  # partial spearmans to extract EF relation (for direction)
  pspear=pcor(scaledf,method='spearman')$estimate
  corest<-pspear[5]
  if(corest<0){
    dif=dif*-1
  }
  
  return(dif)

}

# Next, to derive the statistical significance of observed age effects, we need to test if the two models (one with an age term, one without) are significantly different. We use an ANOVA for this procedure. These p-values will eventually be FDR-corrected.

# chisq test sig. output
DeltaPEstVec_OV_s<-function(x){
  
    # relevant df
  scaledf<-data.frame(cbind(as.numeric(masterdf_sub$overall_psychopathology_4factorv2),as.numeric(masterdf_sub$Age),as.numeric(masterdf_sub$Sex),masterdf_sub$Motion,x))
  colnames(scaledf)<-c('overall_psychopathology_4factorv2','Age','Sex','Motion','varofint')
  
  # no-EF model (segreg ~ sex + motion)
  noTdGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  # EF-included model for measuring difference
  TdGam<-gam(varofint~overall_psychopathology_4factorv2+Sex+Motion+s(Age,k=3),data=scaledf)
  
  # test of dif with anova.gam
  anovaRes<-anova.gam(noTdGam,TdGam,test='Chisq')
  anovaP<-anovaRes$`Pr(>Chi)`
  anovaP2<-unlist(anovaP)
  return(anovaP2[2])
}

DeltaR2EstVec_AM_s<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(masterdf_sub$mood_4factorv2),as.numeric(masterdf_sub$Age),as.numeric(masterdf_sub$Sex),masterdf_sub$Motion,x))
  colnames(scaledf)<-c('mood_4factorv2','Age','Sex','Motion','varofint')
  
  # no-Td model (b.w. ~ sex + motion)
  noTdGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  noTdSum<-summary(noTdGam)
  # Td-included model for measuring difference
  TdGam<-gam(varofint~mood_4factorv2+Sex+Motion+s(Age,k=3),data=scaledf)
  TdSum<-summary(TdGam)
  
  dif<-TdSum$r.sq-noTdSum$r.sq
  
  # partial spearmans to extract EF relation (for direction)
  pspear=pcor(scaledf,method='spearman')$estimate
  corest<-pspear[5]
  if(corest<0){
    dif=dif*-1
  }
  
  return(dif)

}

# chisq test sig. output
DeltaPEstVec_AM_s<-function(x){
  
    # relevant df
  scaledf<-data.frame(cbind(as.numeric(masterdf_sub$mood_4factorv2),as.numeric(masterdf_sub$Age),as.numeric(masterdf_sub$Sex),masterdf_sub$Motion,x))
  colnames(scaledf)<-c('mood_4factorv2','Age','Sex','Motion','varofint')
  
  # no-EF model (segreg ~ sex + motion)
  noTdGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  # EF-included model for measuring difference
  TdGam<-gam(varofint~mood_4factorv2+Sex+Motion+s(Age,k=3),data=scaledf)
  
  # test of dif with anova.gam
  anovaRes<-anova.gam(noTdGam,TdGam,test='Chisq')
  anovaP<-anovaRes$`Pr(>Chi)`
  anovaP2<-unlist(anovaP)
  return(anovaP2[2])

}

DeltaR2EstVec_AM_s<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(masterdf_sub$mood_4factorv2),as.numeric(masterdf_sub$Age),as.numeric(masterdf_sub$Sex),masterdf_sub$Motion,x))
  colnames(scaledf)<-c('mood_4factorv2','Age','Sex','Motion','varofint')
  
  # no-Td model (b.w. ~ sex + motion)
  noTdGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  noTdSum<-summary(noTdGam)
  # Td-included model for measuring difference
  TdGam<-gam(varofint~mood_4factorv2+Sex+Motion+s(Age,k=3),data=scaledf)
  TdSum<-summary(TdGam)
  
  dif<-TdSum$r.sq-noTdSum$r.sq
  
  # partial spearmans to extract EF relation (for direction)
  pspear=pcor(scaledf,method='spearman')$estimate
  corest<-pspear[5]
  if(corest<0){
    dif=dif*-1
  }
  
  return(dif)

}

# chisq test sig. output
DeltaPEstVec_AM_s<-function(x){
  
    # relevant df
  scaledf<-data.frame(cbind(as.numeric(masterdf_sub$mood_4factorv2),as.numeric(masterdf_sub$Age),as.numeric(masterdf_sub$Sex),masterdf_sub$Motion,x))
  colnames(scaledf)<-c('mood_4factorv2','Age','Sex','Motion','varofint')
  
  # no-EF model (segreg ~ sex + motion)
  noTdGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  # EF-included model for measuring difference
  TdGam<-gam(varofint~mood_4factorv2+Sex+Motion+s(Age,k=3),data=scaledf)
  
  # test of dif with anova.gam
  anovaRes<-anova.gam(noTdGam,TdGam,test='Chisq')
  anovaP<-anovaRes$`Pr(>Chi)`
  anovaP2<-unlist(anovaP)
  return(anovaP2[2])

}

# difference in R2 for EF
DeltaR2EstVec_EF_s<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(masterdf_sub$F1_Exec_Comp_Cog_Accuracy),as.numeric(masterdf_sub$Age),as.numeric(masterdf_sub$Sex),masterdf_sub$Motion,x))
  colnames(scaledf)<-c('EF','Age','Sex','Motion','varofint')
  
  # no-EF model (b.w. ~ sex + motion)
  noEFGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  noEFSum<-summary(noEFGam)
  # EF-included model for measuring difference
  EFGam<-gam(varofint~EF+Sex+Motion+s(Age,k=3),data=scaledf)
  EFSum<-summary(EFGam)
  
  dif<-EFSum$r.sq-noEFSum$r.sq
  
  # partial spearmans to extract EF relation (for direction)
  pspear=pcor(scaledf,method='spearman')$estimate
  corest<-pspear[5]
  if(corest<0){
    dif=dif*-1
  }
  
  return(dif)
  
}

# same thing but returning chisq test sig. output for FDR correction instead of hard difference
DeltaPEstVec_EF_s<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(masterdf_sub$F1_Exec_Comp_Cog_Accuracy),as.numeric(masterdf_sub$Age),as.numeric(masterdf_sub$Sex),masterdf_sub$Motion,x))
  colnames(scaledf)<-c('EF','Age','Sex','Motion','varofint')
  
  # no-EF model (segreg ~ sex + motion)
  noEFGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  # EF-included model for measuring difference
  EFGam<-gam(varofint~EF+Sex+Motion+s(Age,k=3),data=scaledf)
  
  # test of dif with anova.gam
  anovaRes<-anova.gam(noEFGam,EFGam,test='Chisq')
  anovaP<-anovaRes$`Pr(>Chi)`
  anovaP2<-unlist(anovaP)
  return(anovaP2[2])
  
}

DeltaR2EstVec_s<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(masterdf_sub$Age),as.numeric(masterdf_sub$Sex),masterdf_sub$Motion,x))
  colnames(scaledf)<-c('Age','Sex','Motion','varofint')
  
  # no-age model (segreg ~ sex + motion)
  noAgeGam<-gam(varofint~Sex+Motion,data=scaledf)
  noAgeSum<-summary(noAgeGam)
  # age-included model for measuring difference
  AgeGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  AgeSum<-summary(AgeGam)
  
  dif<-AgeSum$r.sq-noAgeSum$r.sq
  
  # partial spearmans to extract age relation (for direction)
  pspear=pcor(scaledf,method='spearman')$estimate
  corest<-pspear[4]
  if(corest<0){
    dif=dif*-1
  }
  
  return(dif)
  
}

# Next, to derive the statistical significance of observed age effects, we need to test if the two models (one with an age term, one without) are significantly different. We use an ANOVA for this procedure. These p-values will eventually be FDR-corrected.

# chisq test sig. output
DeltaPEstVec_s<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(masterdf_sub$Age),as.numeric(masterdf_sub$Sex),masterdf_sub$Motion,x))
  colnames(scaledf)<-c('Age','Sex','Motion','varofint')
  
  # no-age model (segreg ~ sex + motion)
  noAgeGam<-gam(varofint~Sex+Motion,data=scaledf)
  # age-included model for measuring difference
  AgeGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  
  # test of dif with anova.gam
  anovaRes<-anova.gam(noAgeGam,AgeGam,test='Chisq')
  anovaP<-anovaRes$`Pr(>Chi)`
  anovaP2<-unlist(anovaP)
  return(anovaP2[2])
  
}
```




```{r}
# JLF names
JLFnames=read.delim('~/miccaiNodeNames.txt',header=F)
JLFInds=read.delim('~/miccaiNodeIndex.txt',header=F)
```


```{r}
# load 'erry thang

### load in demograhics
demo<-read.csv('/cbica/projects/pinesParcels/data/pnc_demo.csv')
ageSex<-data.frame(demo$ageAtScan1,as.factor(demo$sex),demo$scanid,demo$bblid)
subjects<-read.delim('/cbica/projects/pinesParcels/data_psy/PsychSubjs.txt',header = F)


### Collapse Motion metric 
# read in
Rest_Motion_Data <- read.csv("/cbica/projects/pinesParcels/data/n1601_RestQAData_20170714.csv")
NBack_Motion_Data <- read.csv("/cbica/projects/pinesParcels/data/n1601_NBACKQAData_20181001.csv")
Idemo_Motion_Data <- read.csv("/cbica/projects/pinesParcels/data/n1601_idemo_FinalQA_092817.csv")
# combine
motmerge<-merge(Rest_Motion_Data,NBack_Motion_Data,by='bblid')
motmerge<-merge(motmerge,Idemo_Motion_Data,by='bblid')
motmerge$Motion <- (motmerge$restRelMeanRMSMotion + motmerge$nbackRelMeanRMSMotion + motmerge$idemoRelMeanRMSMotion)/3;
motiondf<-data.frame(motmerge$bblid,motmerge$Motion)
colnames(motiondf)<-c('bblid','Motion')

# bring in psychopathology data
psy<-read.csv('/cbica/projects/pinesParcels/data_psy/n1601_goassess_itemwise_bifactor_scores_20161219.csv')
psycor<-read.csv('/cbica/projects/pinesParcels/data_psy/n1601_goassess_itemwise_corrtraits_scores_20161219.csv')

### combine non-fMR data
colnames(subjects)<-c("bblid")
colnames(ageSex)<-c("Age","Sex","scanid","bblid")
df<-merge(subjects,ageSex,by="bblid")
df<-merge(df,motiondf,by='bblid')

df<-merge(df,psy,by='bblid')
df<-merge(df,psycor,by='bblid')


### community solutions guaged in this iteration
community_vec<-seq(2,30)

# big load - output of fc_to_csv.m (all coupling/FC data, pre-organized)
fc<-vroom('/cbica/projects/pinesParcels/results_psy/aggregated_data/fc/master_fcfeats_psy_rounded.csv')

# Merge with non-fMR data into master data frame
masterdf<-merge(fc,df,by='bblid')

# add EF
subjbehav<-read.csv("~/Downloads/n9498_cnb_factor_scores_fr_20170202.csv")
#ef<-data.frame(subjbehav$F1_Exec_Comp_Cog_Accuracy,subjbehav$bblid)
ef<-data.frame(subjbehav$NAR_F1_Exec_Comp_Cog_Accuracy,subjbehav$bblid)
colnames(ef)<-c('F1_Exec_Comp_Cog_Accuracy','bblid')
# merge in
masterdf<-merge(masterdf,ef,by='bblid')

# BU-TD
#BUTD<-read.csv('/cbica/projects/pinesParcels/multiscale_psy/scripts/BUTD.csv',header=F)
#colnames(BUTD)<-c('bblid','BottomUp','TopDown','BUSpeed','TDSpeed')
#masterdf<-merge(masterdf,BUTD,by='bblid')
```

```{r}
# load in rounded subcortical FC feats
fc_sub<-vroom('/cbica/projects/pinesParcels/results_psy/aggregated_data/fc/master_fcfeats_Sub_rounded.csv')
masterdf_sub<-merge(masterdf,fc_sub,by='scanid')
```

```{r}
### Get in Consensus-reference atlas correspondence
rac<-read.csv('/cbica/projects/pinesParcels/results/aggregated_data/fc/network_yCorrespondence_overscales.csv',stringsAsFactors = F)
scalesvec<-as.numeric(rac[2,])
domnetvec<-as.factor(rac[3,])
netpropvec<-as.numeric(rac[4,])
# 17 network version
rac17<-read.csv('/cbica/projects/pinesParcels/results/aggregated_data/fc/network_y17Correspondence_overscales.csv',stringsAsFactors = F)
scalesvec17<-as.numeric(rac17[2,])
domnetvec17<-as.factor(rac17[3,])
netpropvec17<-as.numeric(rac17[4,])

#### read in transmodality
tm<-read.csv('/cbica/projects/pinesParcels/results/aggregated_data/fc/network_transmodality_overscales.csv',stringsAsFactors = F)
colnames(tm)<-tm[1,]
# aaaand remove it so we got everything in its right place
tm<-tm[-c(1),]
tmvec<-as.numeric(tm)
# use median transmodality value to split relatively bimodal distribution
medtrans<-median(tmvec)
# equivalent vector to be overwritten with binary classification of transmodality
tmclass<-tmvec
for (i in 1:length(tmclass)){
  if (tmvec[i]<= medtrans){
    tmclass[i]='unimodal'
  }else{
    tmclass[i]='transmodal'
  }
}
# parse fields of interest 

# indicator of individualized values in dataframe column names
ind='ind'

# indicators of fc feature type. Within and segregation included because the measured length of these index vectors are useful (i.e., a singular value for each network, unlike between-network connectivity)
bwi='_bw_FC_'
wini='_win_FC_'
nsegi='_seg_scale'

# indices of said indicators
indiv=grep(ind,colnames(masterdf))
bwcol=grep(bwi,colnames(masterdf))
wincols=grep(wini,colnames(masterdf))
nsegcols=grep(nsegi,colnames(masterdf))

### Using index combinations, get to dataframe of interest
indiv_bwcols_ind<-intersect(bwcol,indiv)
individ_scalebybw_df<-masterdf[,indiv_bwcols_ind]
bwcolnames<-colnames(individ_scalebybw_df)
indiv_nsegcols_ind<-intersect(nsegcols,indiv)
indiv_wincols_ind<-intersect(wincols,indiv)
individ_scalebywin_df<-masterdf[,indiv_wincols_ind]
# to later use wincolname -> bwcolname mapping to extrapolate if if network is unimodal or transmodal along bwcol indices
wincolnames<-colnames(individ_scalebywin_df)

# subcortical
Subi='_Sub'
Sub=grep(Subi,colnames(masterdf_sub))
rsnb_s_fc=grep('_rsnb_',colnames(masterdf_sub))
emo_s_fc=grep('_emo_',colnames(masterdf_sub))
Sub<-c(Sub,rsnb_s_fc,emo_s_fc)

# the purpose of this chunk is to get average between-network connectivity of each network (average over each network's edges at each scale). We are distilling a bunch of "edges", for which each network has K(scale)-1, to a singular value for each network. There is an easier chunk to follow up top (commented out), and a more complicated but faster-running chunk to follow down below (uncommented) if desired.

# empty array for each nets average b/w con across subjects
bwAvgCon<-matrix(0,790,464)


# simpler version for easier replication - this still has the annoying part where "_"'s are added in and taken out though. Needed to distinguish scale 1 from 10, 2 from 20, etc.

# simpler but about 5x slower....

## loop over each scale
 for (K in 2:30){
 # Make index of where values from this K should go
   K_start=((K-1)*(K))/2
   K_end=(((K-1)*(K))/2)+K-1
   Kind<-K_start:K_end
   # index which values are at this scale
   scaleStr=paste('scale',K,'_',sep='')
   scaleCols_inds=grep(scaleStr,colnames(masterdf))
   scaleK_bw_indivi_cols_inds<-intersect(indiv_bwcols_ind,scaleCols_inds)
   # extract within and between colnames at this scale for within->b/w binarized transmodality mapping
    bwcolnames_thisScale_inds<-grep((paste('scale',K,'_',sep='')),bwcolnames)
    bwcolnames_thisScale=bwcolnames[bwcolnames_thisScale_inds]
    
    # remove scale number from strings so we're not picking up on those
    bwcolnames_thisScale_split<-strsplit(bwcolnames_thisScale,"nets")
    bwnetnames_thisScale<-sapply(bwcolnames_thisScale_split, "[[" , 2)
    # add another fucking set of underscores to all of these colnames so 1's dont pick up 10s, 2s 20s.
   bwnetnames_thisScale_extended<-paste('ind_bw_FC_scale',K,'_nets_',bwnetnames_thisScale,'_',sep='')
   # extra goddamn underscores have to go here and be removed later
   bwcolnames_thisScale_split<-strsplit(bwcolnames_thisScale,"nets")
   
   for (N in 1:K){
     # generate index for where values for this network at this scale should reside
     # start from K index
     Nind<-Kind[N]
     # get index for this N in terms of masterdf (collapse | to match multiple patterns)
     Ncolnames<-grep(as.character(paste('_',N,'_',sep='')),bwnetnames_thisScale_extended,value=T)
     # cut terminal underscore
     Ncolnames_circumcised<-substr(Ncolnames,1,nchar(Ncolnames)-1)
     # cut last extraneous underscore: after scaleX_nets_
     scaleNetStr=paste(scaleStr,'nets_',sep='')
     desired_scaleNetStr=paste(scaleStr,'nets',sep='')
     # make the subs
     Ncolnames_circumcised_shortened<-gsub(scaleNetStr,desired_scaleNetStr,Ncolnames_circumcised)
     # find corresponding spots in masterdf
     # paste("x$") added for exact matches only (end anchor)
     N_indices<-sapply(Ncolnames_circumcised_shortened,function(y) grep(paste(y,'$',sep=''),colnames(masterdf)))
     # extract all columns of interest for each subject
     N_edges_at_this_scale<-cbind(masterdf[,N_indices])
     # get corresponding columns, average over
     avg_bw=rowMeans(N_edges_at_this_scale)
     # for bw-based gams later - convert all b/w cons for a net to avg b/w for each subj
     bwAvgCon[,Nind]=avg_bw
   }
 }


```

```{r}
# subcort relationships

### use this block to control which subcort structure
Subi_s='R_Thalamus_Proper'
Sub_s=grep(Subi_s,colnames(masterdf_sub))
# remove redundant values and autocorrelation (value of 1 for all)
Subi_s2=paste0(Subi_s,'_',Subi_s)
Sub_s2=grep(Subi_s2,colnames(masterdf_sub))
# get location of columns
intersection=intersect(Sub,Sub_s)
# remove two autocorrelation columns
intersection=setdiff(intersection,Sub_s2)
# out of subcort-subcort, remove redundant instances
# (i.e., amy_l_amy_r,amy_r_amy_l)
# underscore denotes first subCort in colName (i.e., amyg_l_)
Subi_s_u=paste0(Subi_s,'_')
SubCortIntersection=intersection[465:516]
Sub_s_u=grep(Subi_s_u,colnames(masterdf_sub)[SubCortIntersection])
Non_redundant_subcort_indices<-SubCortIntersection[Sub_s_u]
Cort_subcort_indices<-intersection[1:464]
# final intersection
fintersection=c(Cort_subcort_indices,Non_redundant_subcort_indices)
Sub_df<-masterdf_sub[,fintersection]
SubColnames<-colnames(Sub_df)
###

# initialize output vectors
avg_bw_deltaR2_OV<-rep(0,length=length(Sub_df))
avg_bw_deltaP_OV<-rep(0,length=length(Sub_df))
avg_bw_deltaR2_AM<-rep(0,length=length(Sub_df))
avg_bw_deltaP_AM<-rep(0,length=length(Sub_df))
avg_bw_deltaR2_EF<-rep(0,length=length(Sub_df))
avg_bw_deltaP_EF<-rep(0,length=length(Sub_df))
DeltaR2_age<-rep(0,length=length(Sub_df))
DeltaP_age<-rep(0,length=length(Sub_df))

#add on covariate columns
Sub_df$Sex<-masterdf_sub$Sex
Sub_df$Motion<-masterdf_sub$Motion

#for i in 6888, -2 because age sex motion columns sit at the end
for (i in 1:(length(Sub_df)-2)){
  # borrowing colnames from indiv_nsegcols to keep network mappings
  x<-colnames(Sub_df[i])
  # is it the diagonal of an fc matrix?
  rangeFC<-range(Sub_df[,i])
  if ((rangeFC[1]-rangeFC[2])!=0){
  avg_bw_deltaR2_OV[i]<-DeltaR2EstVec_OV_s(Sub_df[i])
  avg_bw_deltaP_OV[i]<-DeltaPEstVec_OV_s(Sub_df[i])
  avg_bw_deltaR2_EF[i]<-DeltaR2EstVec_EF_s(Sub_df[i])
  avg_bw_deltaP_EF[i]<-DeltaPEstVec_EF_s(Sub_df[i])
  avg_bw_deltaR2_AM[i]<-DeltaR2EstVec_AM_s(Sub_df[i])
  avg_bw_deltaP_AM[i]<-DeltaPEstVec_AM_s(Sub_df[i])
  # age effects
  DeltaR2_age[i]<-DeltaR2EstVec_s(Sub_df[i])
  DeltaP_age[i]<-DeltaPEstVec_s(Sub_df[i])
  }
}

# transmodality mappings for networks, null for subcort-subcort
adaptedtmvec=c(tmvec,rep(8,26))
adaptedDomnetVec<-domnetvec
levels(adaptedDomnetVec)<-c(levels(domnetvec),'SubCort')
adaptedDomnetVec[465:490]=rep('SubCort',26)

# bring all of the filled-out veectors together into a dataframe for plotting
Sub_S_df<-data.frame(avg_bw_deltaR2_OV,avg_bw_deltaP_OV,avg_bw_deltaR2_EF,avg_bw_deltaP_EF,avg_bw_deltaR2_AM,avg_bw_deltaP_AM,DeltaR2_age,DeltaP_age,adaptedtmvec,adaptedDomnetVec)

### vector for EF sig.
Sub_S_df$domnetvecSig<-'NonSig'
corrected<-p.adjust(avg_bw_deltaP_EF,method='fdr')
# network-level sig vector
NL_sigVec<-logical(490)
NL_sigVec[corrected<0.05]<-TRUE
Sub_S_df$domnetvecSig[NL_sigVec]<-as.character(Sub_S_df$adaptedDomnetVec[NL_sigVec])

# order for plot legend
Sub_S_df$domnetvecSig<-as.factor(Sub_S_df$domnetvecSig)
Sub_S_df$domnetvecSig<-factor(Sub_S_df$domnetvecSig,levels=c("Motor","Visual","DA","VA","Limbic","FP","DM","NonSig","SubCort"),labels=c("Motor","Visual","DA","VA","Limbic","FP","DM","NonSig.","SubCort"))

# for EF
EF<-ggplot(Sub_S_df,aes(adaptedtmvec,avg_bw_deltaR2_EF)) + geom_point(size=6,alpha=.8,aes(color=domnetvecSig))+ scale_color_manual(values=c('#3281ab','#670068','#007500','#b61ad0','#b8cf86','#d77d00','#c1253c','gray80','gray40')) + xlab("Functional Hierarchy")+ ylab(expression(paste('EF Effect (',Delta,R^2[adj],')',sep=''))) +theme_classic(base_size = 40) +guides(color=guide_legend(title="Yeo 7 Overlap"))+theme(plot.margin=margin(b=3,t=.1,l=.1,r=.1, unit='cm'), legend.position=c(.42,-.24), legend.direction = "horizontal",legend.title=element_text(size=30),legend.text=element_text(size=30))+labs(title=paste(Subi_s))

### vector for AM sig.
Sub_S_df$domnetvecSig<-'NonSig'
corrected<-p.adjust(avg_bw_deltaP_AM,method='fdr')
# network-level sig vector
NL_sigVec<-logical(490)
NL_sigVec[corrected<0.05]<-TRUE
Sub_S_df$domnetvecSig[NL_sigVec]<-as.character(Sub_S_df$adaptedDomnetVec[NL_sigVec])

# order for plot legend
Sub_S_df$domnetvecSig<-as.factor(Sub_S_df$domnetvecSig)
Sub_S_df$domnetvecSig<-factor(Sub_S_df$domnetvecSig,levels=c("Motor","Visual","DA","VA","Limbic","FP","DM","NonSig","SubCort"),labels=c("Motor","Visual","DA","VA","Limbic","FP","DM","NonSig.","SubCort"))
# for AM
AM<-ggplot(Sub_S_df,aes(adaptedtmvec,avg_bw_deltaR2_AM)) + geom_point(size=6,alpha=.8,aes(color=domnetvecSig))+ scale_color_manual(values=c('#3281ab','#670068','#007500','#b61ad0','#b8cf86','#d77d00','#c1253c','gray80','gray40')) + xlab("Functional Hierarchy")+ ylab(expression(paste('AM Effect (',Delta,R^2[adj],')',sep=''))) +theme_classic(base_size = 40) +guides(color=guide_legend(title="Yeo 7 Overlap"))+theme(plot.margin=margin(b=3,t=.1,l=.1,r=.1, unit='cm'), legend.position=c(.42,-.24), legend.direction = "horizontal",legend.title=element_text(size=30),legend.text=element_text(size=30))+labs(title=paste(Subi_s))

# and for age
Sub_S_df$domnetvecSig<-'NonSig'
corrected<-p.adjust(DeltaP_age,method='fdr')
# network-level sig vector
NL_sigVec<-logical(490)
NL_sigVec[corrected<0.05]<-TRUE
Sub_S_df$domnetvecSig[NL_sigVec]<-as.character(Sub_S_df$adaptedDomnetVec[NL_sigVec])

# order for plot legend
Sub_S_df$domnetvecSig<-as.factor(Sub_S_df$domnetvecSig)
Sub_S_df$domnetvecSig<-factor(Sub_S_df$domnetvecSig,levels=c("Motor","Visual","DA","VA","Limbic","FP","DM","NonSig","SubCort"),labels=c("Motor","Visual","DA","VA","Limbic","FP","DM","NonSig.","SubCort"))
# for AM
AGE<-ggplot(Sub_S_df,aes(adaptedtmvec,DeltaR2_age)) + geom_point(size=6,alpha=.8,aes(color=domnetvecSig))+ scale_color_manual(values=c('#3281ab','#670068','#007500','#b61ad0','#b8cf86','#d77d00','#c1253c','gray80','gray40')) + xlab("Functional Hierarchy")+ ylab(expression(paste('Age Effect (',Delta,R^2[adj],')',sep=''))) +theme_classic(base_size = 40) +guides(color=guide_legend(title="Yeo 7 Overlap"))+theme(plot.margin=margin(b=3,t=.1,l=.1,r=.1, unit='cm'), legend.position=c(.42,-.24), legend.direction = "horizontal",legend.title=element_text(size=30),legend.text=element_text(size=30))+labs(title=paste(Subi_s))
```

```{r}
# read in second gradient
#### read in grad2
#occm<-read.csv('/cbica/projects/pinesParcels/results/aggregated_data/fc/network_grad2_overscales.csv',stringsAsFactors = F)
#colnames(occm)<-occm[1,]
# aaaand remove it
#occm<-occm[-c(1),]
#occvec<-as.numeric(occm)
```

```{r}
# calculate age effects for each network. This is the part where we loop over all networks to get all our measures of interest, delta R^2 and associated stat. significance, the slope of estimated age effects across the age-range of our sample, etc.

# initialize output vectors
avg_bw_deltaR2_OV<-rep(0,length=length(masterdf[,indiv_wincols_ind]))
avg_bw_deltaP_OV<-rep(0,length=length(masterdf[,indiv_wincols_ind]))
avg_bw_deltaR2_FE<-rep(0,length=length(masterdf[,indiv_wincols_ind]))
avg_bw_deltaP_FE<-rep(0,length=length(masterdf[,indiv_wincols_ind]))
avg_bw_deltaR2_AM<-rep(0,length=length(masterdf[,indiv_wincols_ind]))
avg_bw_deltaP_AM<-rep(0,length=length(masterdf[,indiv_wincols_ind]))
avg_bw_deltaR2_PS<-rep(0,length=length(masterdf[,indiv_wincols_ind]))
avg_bw_deltaP_PS<-rep(0,length=length(masterdf[,indiv_wincols_ind]))
avg_bw_deltaR2_EX<-rep(0,length=length(masterdf[,indiv_wincols_ind]))
avg_bw_deltaP_EX<-rep(0,length=length(masterdf[,indiv_wincols_ind]))

avg_bw_deltaR2_age<-rep(0,length=length(masterdf[,indiv_wincols_ind]))
avg_bw_deltaP_age<-rep(0,length=length(masterdf[,indiv_wincols_ind]))

# borrowing colnames from indiv_nsegcols to keep network/scale ordering/mappings
colnames(bwAvgCon)<-gsub("_win_","_avgBw_",colnames(masterdf[,indiv_wincols_ind]))
bwAvgCondf<-data.frame(bwAvgCon)
#add on covariate columns
bwAvgCondf$Sex<-masterdf$Sex
bwAvgCondf$Motion<-masterdf$Motion
#for i in 464, -3 because age sex motion columns sit at the end
for (i in 1:(length(bwAvgCondf)-2)){
  # borrowing colnames from indiv_nsegcols to keep network mappings
  x<-colnames(bwAvgCondf[i])
  avg_bw_deltaR2_OV[i]<-DeltaR2EstVec_OV(bwAvgCondf[i])
  avg_bw_deltaP_OV[i]<-DeltaPEstVec_OV(bwAvgCondf[i])
  avg_bw_deltaR2_FE[i]<-DeltaR2EstVec_FE(bwAvgCondf[i])
  avg_bw_deltaP_FE[i]<-DeltaPEstVec_FE(bwAvgCondf[i])
  avg_bw_deltaR2_AM[i]<-DeltaR2EstVec_AM(bwAvgCondf[i])
  avg_bw_deltaP_AM[i]<-DeltaPEstVec_AM(bwAvgCondf[i])
  avg_bw_deltaR2_PS[i]<-DeltaR2EstVec_PS(bwAvgCondf[i])
  avg_bw_deltaP_PS[i]<-DeltaPEstVec_PS(bwAvgCondf[i])
  avg_bw_deltaR2_EX[i]<-DeltaR2EstVec_EX(bwAvgCondf[i])
  avg_bw_deltaP_EX[i]<-DeltaPEstVec_EX(bwAvgCondf[i])
  avg_bw_deltaR2_age[i]<-DeltaR2EstVec(bwAvgCondf[i])
  avg_bw_deltaP_age[i]<-DeltaPEstVec(bwAvgCondf[i])
}

```

```{r}
# bring all of the filled-out veectors together into a dataframe for plotting
bwdf<-data.frame(tmvec,scalesvec,domnetvec,domnetvec17,netpropvec,avg_bw_deltaR2_OV,avg_bw_deltaP_OV,avg_bw_deltaR2_FE,avg_bw_deltaP_FE,avg_bw_deltaR2_AM,avg_bw_deltaP_AM,avg_bw_deltaR2_PS,avg_bw_deltaP_PS,avg_bw_deltaR2_EX,avg_bw_deltaP_EX,avg_bw_deltaR2_age,avg_bw_deltaP_age,occvec,EFDR2vec)
```

```{r}
# transient chunk
library(plot3Drgl)
bwdf$domnetCols<-as.character(bwdf$domnetvec)
bwdf$domnetCols[bwdf$domnetCols=='DM']<-"red"
bwdf$domnetCols[bwdf$domnetCols=='Motor']<-"blue"
bwdf$domnetCols[bwdf$domnetCols=='FP']<-"orange"
bwdf$domnetCols[bwdf$domnetCols=='DA']<-"green"
bwdf$domnetCols[bwdf$domnetCols=='VA']<-"pink"
bwdf$domnetCols[bwdf$domnetCols=='Visual']<-"purple"
bwdf$domnetCols[bwdf$domnetCols=='Limbic']<-"grey"

plot3d(size=12,x=bwdf$tmvec,y=bwdf$EFDR2vec,col=bwdf$domnetCols,z=bwdf$scalesvec,ylab="EF Effect",xlab="Functional Hierarchy",zlab="Scale")

# For scale-dependent effects, we isolate the most unimodal (SOM_A) and transmodal (DM_B) Yeo17 groups across scales to compare the relative impact of scale upon their age-relations.

# figure 5c stuff - Age Effect * Scale * Transmodality
# lms for stats
AM_FP_gam<-gam(avg_bw_deltaR2_AM~s(scalesvec,k=3),data=bwdf[bwdf$domnetvec=='FP',])
EF_FP_gam<-gam(EFDR2vec~s(scalesvec,k=3),data=bwdf[bwdf$domnetvec=='FP',])
summary(AM_FP_gam)
summary(EF_FP_gam)

ggplot(data=subset(bwdf,domnetvec=='FP'),aes(scalesvec,avg_bw_deltaR2_AM)) + xlab("# of Networks") + ylab(expression(paste('AM Effect (',Delta,R^2[adj],')'))) +theme_classic(base_size = 28)+
geom_smooth(data=subset(bwdf,domnetvec=='FP'),method='gam',formula = y~s(x,k=3),size=2)+geom_point(col='orange',size=3)

ggplot(data=subset(bwdf,domnetvec=='FP'),aes(scalesvec,EFDR2vec)) + xlab("# of Networks") + ylab(expression(paste('EF Effect (',Delta,R^2[adj],')'))) +theme_classic(base_size = 28)+
geom_smooth(data=subset(bwdf,domnetvec=='FP'),method='gam',formula = y~s(x,k=3),size=2)+geom_point(col='orange',size=3)
```

```{r, fig.width=11,fig.height=11}
# Figure 3C
ggplot(bwdf,aes(tmvec,avg_bw_deltaR2_age)) + geom_point(size=6,alpha=.8,aes(color=domnetvecSig))+ scale_color_manual(values=c('#3281ab','#670068','#007500','#b61ad0','#b8cf86','#d77d00','#c1253c','gray80')) + xlab("Functional Hierarchy") + ylab(expression(paste('Age Effect (',Delta,R^2[adj],')',sep=''))) +theme_classic(base_size = 40) +guides(color=guide_legend(title="Yeo 7 Overlap"))+theme(plot.margin=margin(b=3,t=.1,l=.1,r=.1, unit='cm'), legend.position=c(.42,-.24),legend.direction = "horizontal",legend.title=element_text(size=30),legend.text=element_text(size=30))+geom_smooth(method='lm',color='black',size=3)
```

```{r}
library(mgcv)
library(lme4)
# for interaction modeling, melt data
bwAvgCondf$Age<-masterdf$Age
bwAvgCondf$bblid<-as.factor(masterdf$bblid)
m_bwcon<-melt(bwAvgCondf,id=c("Sex","Motion","Age","bblid"))
m_bwcon$Transmodality<-rep(tmvec,each=790)
m_bwcon$Scale<-rep(scalesvec,each=790)
m_bwcon$Psychopathology<-rep(masterdf$overall_psychopathology_4factorv2,times=464)
TMPGLM<-lmer(value~Transmodality*Psychopathology+Sex+Motion+Scale+Age+(1|bblid),data=m_bwcon)

# nonsmooth version
TM_OV_gam<-gam(value~ti(Transmodality)+ti(Psychopathology)+ti(Transmodality,Psychopathology)+Sex+Motion+Scale+ti(Age),data=m_bwcon)
```

```{r}
### vector for OV sig.
bwdf$domnetvecSig<-'NonSig'
corrected<-p.adjust(avg_bw_deltaP_OV,method='fdr')
# network-level sig vector
NL_sigVec<-logical(464)
NL_sigVec[corrected<0.05]<-TRUE
bwdf$domnetvecSig[NL_sigVec]<-as.character(bwdf$domnetvec[NL_sigVec])
# order for plot legend
bwdf$domnetvecSig<-as.factor(bwdf$domnetvecSig)
bwdf$domnetvecSig<-factor(bwdf$domnetvecSig,levels=c("Motor","Visual","DA","VA","Limbic","FP","DM","NonSig"),labels=c("Motor","Visual","DA","VA","Limbic","FP","DM","NonSig."))

OV<-ggplot(bwdf,aes(tmvec,avg_bw_deltaR2_OV)) + 
geom_point(size=4,alpha=.8,aes(color=domnetvecSig)) + scale_color_manual(values=c('#3281ab','#670068','#007500','#b61ad0','#b8cf86','#d77d00','#c1253c','gray80'))+ 
xlab("Transmodality") + ylab(expression(paste('Overall (',Delta,R^2[adj],')',sep=''))) +theme_classic(base_size = 40) +guides(color=guide_legend(title="Yeo 7 Overlap"))+theme(plot.margin=margin(b=3,t=.1,l=.1,r=.1, unit='cm'), legend.position=c(.42,-.16),legend.direction = "horizontal",legend.title=element_text(size=30),legend.text=element_text(size=30))+geom_smooth(method='lm',color='black',size=3)

### vector for FE sig
bwdf$domnetvecSig<-'NonSig'
corrected<-p.adjust(avg_bw_deltaP_FE,method='fdr')
# network-level sig vector
NL_sigVec<-logical(464)
NL_sigVec[corrected<0.05]<-TRUE
bwdf$domnetvecSig[NL_sigVec]<-as.character(bwdf$domnetvec[NL_sigVec])
# order for plot legend
bwdf$domnetvecSig<-as.factor(bwdf$domnetvecSig)
bwdf$domnetvecSig<-factor(bwdf$domnetvecSig,levels=c("Motor","Visual","DA","VA","Limbic","FP","DM","NonSig"),labels=c("Motor","Visual","DA","VA","Limbic","FP","DM","NonSig."))


FE<-ggplot(bwdf,aes(tmvec,avg_bw_deltaR2_FE)) + geom_point(size=6,alpha=.8,aes(color=domnetvecSig))+ scale_color_manual(values=c('#3281ab','#670068','#007500','#b61ad0','#b8cf86','#d77d00','#c1253c','gray80')) + xlab("Transmodality") + ylab(expression(paste('Fear (',Delta,R^2[adj],')',sep=''))) +theme_classic(base_size = 40) +guides(color=guide_legend(title="Yeo 7 Overlap"))+theme(plot.margin=margin(b=3,t=.1,l=.1,r=.1, unit='cm'), legend.position=c(.42,-.16),legend.direction = "horizontal",legend.title=element_text(size=30),legend.text=element_text(size=30))+geom_smooth(method='lm',color='black',size=3)

### vector for AM sig
bwdf$domnetvecSig<-'NonSig'
corrected<-p.adjust(avg_bw_deltaP_AM,method='fdr')
# network-level sig vector
NL_sigVec<-logical(464)
NL_sigVec[corrected<0.05]<-TRUE
bwdf$domnetvecSig[NL_sigVec]<-as.character(bwdf$domnetvec[NL_sigVec])
# order for plot legend
bwdf$domnetvecSig<-as.factor(bwdf$domnetvecSig)
bwdf$domnetvecSig<-factor(bwdf$domnetvecSig,levels=c("Motor","Visual","DA","VA","Limbic","FP","DM","NonSig"),labels=c("Motor","Visual","DA","VA","Limbic","FP","DM","NonSig."))

AM<-ggplot(bwdf,aes(tmvec,avg_bw_deltaR2_AM)) + geom_point(size=6,alpha=.8,aes(color=domnetvecSig))+ scale_color_manual(values=c('#3281ab','#670068','#007500','#b61ad0','#b8cf86','#d77d00','#c1253c','gray80')) + xlab("Transmodality") + ylab(expression(paste('Anx.-Mis. (',Delta,R^2[adj],')',sep=''))) +theme_classic(base_size = 40) +guides(color=guide_legend(title="Yeo 7 Overlap"))+theme(plot.margin=margin(b=3,t=.1,l=.1,r=.1, unit='cm'), legend.position=c(.42,-.16),legend.direction = "horizontal",legend.title=element_text(size=30),legend.text=element_text(size=30))+geom_smooth(method='lm',color='black',size=3)

AM_OCC<-ggplot(bwdf,aes(occvec,avg_bw_deltaR2_AM)) + geom_point(size=6,alpha=.8,aes(color=domnetvecSig))+ scale_color_manual(values=c('#3281ab','#670068','#007500','#b61ad0','#b8cf86','#d77d00','#c1253c','gray80')) + xlab("PG2") + ylab(expression(paste('Anx.-Mis. (',Delta,R^2[adj],')',sep=''))) +theme_classic(base_size = 40) +guides(color=guide_legend(title="Yeo 7 Overlap"))+theme(plot.margin=margin(b=3,t=.1,l=.1,r=.1, unit='cm'), legend.position=c(.42,-.16),legend.direction = "horizontal",legend.title=element_text(size=30),legend.text=element_text(size=30))+geom_smooth(method='lm',color='black',size=3)

### vector for PS sig
bwdf$domnetvecSig<-'NonSig'
corrected<-p.adjust(avg_bw_deltaP_PS,method='fdr')
# network-level sig vector
NL_sigVec<-logical(464)
NL_sigVec[corrected<0.05]<-TRUE
bwdf$domnetvecSig[NL_sigVec]<-as.character(bwdf$domnetvec[NL_sigVec])
# order for plot legend
bwdf$domnetvecSig<-as.factor(bwdf$domnetvecSig)
bwdf$domnetvecSig<-factor(bwdf$domnetvecSig,levels=c("Motor","Visual","DA","VA","Limbic","FP","DM","NonSig"),labels=c("Motor","Visual","DA","VA","Limbic","FP","DM","NonSig."))

PS<-ggplot(bwdf,aes(tmvec,avg_bw_deltaR2_PS)) + geom_point(size=6,alpha=.8,aes(color=domnetvecSig))+ scale_color_manual(values=c('#3281ab','#670068','#007500','#b61ad0','#b8cf86','#d77d00','#c1253c','gray80')) + xlab("Transmodality") + ylab(expression(paste('Psychosis (',Delta,R^2[adj],')',sep=''))) +theme_classic(base_size = 40) +guides(color=guide_legend(title="Yeo 7 Overlap"))+theme(plot.margin=margin(b=3,t=.1,l=.1,r=.1, unit='cm'), legend.position=c(.42,-.16),legend.direction = "horizontal",legend.title=element_text(size=30),legend.text=element_text(size=30))


### vector for EX sig
bwdf$domnetvecSig<-'NonSig'
corrected<-p.adjust(avg_bw_deltaP_EX,method='fdr')
# network-level sig vector
NL_sigVec<-logical(464)
NL_sigVec[corrected<0.05]<-TRUE
bwdf$domnetvecSig[NL_sigVec]<-as.character(bwdf$domnetvec[NL_sigVec])
# order for plot legend
bwdf$domnetvecSig<-as.factor(bwdf$domnetvecSig)
bwdf$domnetvecSig<-factor(bwdf$domnetvecSig,levels=c("Motor","Visual","DA","VA","Limbic","FP","DM","NonSig"),labels=c("Motor","Visual","DA","VA","Limbic","FP","DM","NonSig."))

EX<-ggplot(bwdf,aes(tmvec,avg_bw_deltaR2_EX)) + geom_point(size=6,alpha=.8,aes(color=domnetvecSig))+ scale_color_manual(values=c('#3281ab','#670068','#007500','#b61ad0','#b8cf86','#d77d00','#c1253c','gray80')) + xlab("Transmodality") + ylab(expression(paste('External (',Delta,R^2[adj],')',sep=''))) +theme_classic(base_size = 40) +guides(color=guide_legend(title="Yeo 7 Overlap"))+theme(plot.margin=margin(b=3,t=.1,l=.1,r=.1, unit='cm'), legend.position=c(.42,-.16),legend.direction = "horizontal",legend.title=element_text(size=30),legend.text=element_text(size=30))

```

```{r}
# extract edge df
indiv_bwcols_ind<-intersect(bwcol,indiv)
individ_scalebybw_df<-masterdf[,indiv_bwcols_ind]
```

```{r}
# combine age, motion, and Psychopath scores with edges
AgeMotOV<-cbind(masterdf[,indiv_bwcols_ind],masterdf$Age,masterdf$Motion,masterdf$mood_4factorv2)
# write out for scikit learn
write.table(AgeMotOV,'/cbica/projects/pinesParcels/results_psy/EffectVecs/AgeMotOV',sep=',', col.names = F,quote = F,row.names=F)
```

```{r}
# combine age, motion, and Psychopath scores with network-level measures
AgeMotOV_NetLevel<-cbind(bwAvgCon,masterdf$Age,masterdf$Motion,masterdf$overall_psychopathology_4factorv2)
# write out for scikit learn
write.table(AgeMotOV_NetLevel,'/cbica/projects/pinesParcels/results_psy/EffectVecs/AgeMotOV_NetLevel',sep=',', col.names = F,quote = F,row.names=F)
```

```{r}
#### This measures all the pairwise relations (edges)
ageDR2vec_OV<-rep(0,length(colnames(individ_scalebybw_df)))
ageDR2vec_FE=rep(0,length(colnames(individ_scalebybw_df)))
ageDR2vec_AM<-rep(0,length(colnames(individ_scalebybw_df)))
ageDR2vec_PS<-rep(0,length(colnames(individ_scalebybw_df)))
ageDR2vec_EX=rep(0,length(colnames(individ_scalebybw_df)))

# for recording net1 and net2 tm
net1tmvec=rep(0,length(colnames(individ_scalebybw_df)))
net2tmvec=rep(0,length(colnames(individ_scalebybw_df)))
tmdifvec=rep(0,length(colnames(individ_scalebybw_df)))
# this is to look at how finer scales confer networks that are less different
scalevec=rep(0,length(colnames(individ_scalebybw_df)))
# record net types
Net1Vec=rep(0,length(colnames(individ_scalebybw_df)))
Net2Vec=rep(0,length(colnames(individ_scalebybw_df)))
Net1Vec17=rep(0,length(colnames(individ_scalebybw_df)))
Net2Vec17=rep(0,length(colnames(individ_scalebybw_df)))

## for all b/w cols - 7/9/21
for (i in 1:length(colnames(individ_scalebybw_df))){
    # extract column name. Will parse column name to determine nature of #connection
    curcolname<-colnames(individ_scalebybw_df)[i]
    splitname<-unlist(strsplit(curcolname,'_'))
    scalefield=splitname[4]
    net1field=splitname[5]
    net2field=splitname[7]
    # doctor up scale and net1field so they are exclusively the value of #interest
    scale=as.numeric(unlist(strsplit(scalefield,'e'))[2])
    net1=unlist(strsplit(net1field,'s'))[2]
    net2=net2field 
    # helping phriendly index
    K_start=((scale-1)*(scale))/2
    K_end=(((scale-1)*(scale))/2)+scale-1
    Kind<-K_start:K_end
    # get TM values of both nets at this scale
    tm1=tmvec[Kind[as.numeric(net1)]]
    tm2=tmvec[Kind[as.numeric(net2)]]
    net1tmvec[i]<-tm1
    net2tmvec[i]<-tm2
    # absolute value as directionality is meaningless here
    tmdif=abs(tm1-tm2)
    # get position in master df of this column (need to use \b for exact matches #only)
    # added first b 11-9, works if remove
    curcolnameexact<-paste('\\b',curcolname,'\\b',sep='')
    colindex<-grep(curcolnameexact,colnames(masterdf))
    
    # save to respective vectors
    tmdifvec[i]<-tmdif
    # accompanying scalevec so we can look at the typical transmodality #difference at each scale
    scalevec[i]=scale
    
    # record Networks assayed in terms of yeo7
    y7lab1=domnetvec[Kind[as.numeric(net1)]]
    y7lab2=domnetvec[Kind[as.numeric(net2)]]
    y17lab1=domnetvec17[Kind[as.numeric(net1)]]
    y17lab2=domnetvec17[Kind[as.numeric(net2)]]
    Net1Vec[i]<-as.character(y7lab1)
    Net2Vec[i]<-as.character(y7lab2)
    Net1Vec17[i]<-as.character(y17lab1)
    Net2Vec17[i]<-as.character(y17lab2)
    
    # delta r2 for age
    ageDR2vec_OV[i]<-DeltaR2EstVec_OV(masterdf[,colindex])
    ageDR2vec_FE[i]<-DeltaR2EstVec_FE(masterdf[,colindex])
    ageDR2vec_AM[i]<-DeltaR2EstVec_AM(masterdf[,colindex])
    ageDR2vec_PS[i]<-DeltaR2EstVec_PS(masterdf[,colindex])
    ageDR2vec_EX[i]<-DeltaR2EstVec_EX(masterdf[,colindex])
    #####################################
}



# get vectors into a dataframe
BwAgeCorTMDifDf<-data.frame(tmdifvec,scalevec,Net1Vec,Net2Vec,Net1Vec17,Net2Vec17,ageDR2vec_OV,ageDR2vec_EX,ageDR2vec_PS,net1tmvec,net2tmvec,ageDR2vec_AM)

# ycolors
ycolors=c('#3281ab','#670068','#007500','#b61ad0','#b8cf86','#d77d00','#c1253c')
Y7vec<-c('Motor','Visual','DA','VA','Limbic','FP','DM')
```

```{r}
# overall
ggplot(BwAgeCorTMDifDf,aes(x=tmdifvec,y=ageDR2vec_OV))+ geom_text(data=BwAgeCorTMDifDf,size=10,label="\u25D6",family="Arial Unicode MS",aes(x=tmdifvec,y=ageDR2vec_OV,color=Net1Vec))+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(data=BwAgeCorTMDifDf,aes(x=tmdifvec,y=ageDR2vec_OV,color=Net2Vec),size=10,label="\u25D7",family="Arial Unicode MS")+theme(legend.position = "none") + xlab('Transmodality Difference') + ylab(expression(paste('Overall Effect (',Delta,R^2[adj],')')))+theme_classic(base_size = 40)+theme(legend.position = "none")+geom_smooth(method='lm',color='black',size=2)
```


```{r}
# make a double df for symmetry - net1 and net2tmvec repeated in opposite ordering
BwAgeCorTMDifDf2<-BwAgeCorTMDifDf
BwAgeCorTMDifDf2$net1tmvec<-BwAgeCorTMDifDf$net2tmvec
BwAgeCorTMDifDf2$net2tmvec<-BwAgeCorTMDifDf$net1tmvec

# "stacked" df
doubleBwAgeCorTMDifDf<-rbind(BwAgeCorTMDifDf2,BwAgeCorTMDifDf)

# model the surface
g2 <- gam(ageDR2vec_OV ~ te(net2tmvec,net1tmvec,k=4),data = doubleBwAgeCorTMDifDf)

gg_tensor(g2)+theme_classic(base_size = 40) +theme(legend.text=element_text(size=30),legend.key.width =unit(3.5,"cm"),legend.title = element_text(size=30))+scale_fill_gradient2(low = "blue",high = "red",mid = "white",midpoint = 0,name=expression(paste('Overall Psych. Effect (',Delta,R^2[adj],')')),guide = guide_colorbar(legend.position='top',title.position="top",ticks.colour = "gray50", ticks.linewidth = 7))+ggtitle("")+xlab("Functional Hierarchy")+ylab("Functional Hierarchy")+geom_vline(xintercept = mean(range(doubleBwAgeCorTMDifDf$net1tmvec)),linetype='dashed',size=1.5)+geom_hline(yintercept = mean(range(doubleBwAgeCorTMDifDf$net1tmvec)),linetype='dashed',size=1.5)+theme(legend.position='top')

```

```{r}
# External
ggplot(BwAgeCorTMDifDf,aes(x=tmdifvec,y=ageDR2vec_EX))+ geom_text(data=BwAgeCorTMDifDf,size=10,label="\u25D6",family="Arial Unicode MS",aes(x=tmdifvec,y=ageDR2vec_EX,color=Net1Vec))+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(data=BwAgeCorTMDifDf,aes(x=tmdifvec,y=ageDR2vec_EX,color=Net2Vec),size=10,label="\u25D7",family="Arial Unicode MS")+theme(legend.position = "none") + xlab('Transmodality Difference') + ylab(expression(paste('External Effect (',Delta,R^2[adj],')')))+theme_classic(base_size = 40)+theme(legend.position = "none")+geom_smooth(method='lm',color='black',size=2)


g2 <- gam(ageDR2vec_EX ~ te(net2tmvec,net1tmvec,k=4),data = doubleBwAgeCorTMDifDf)

gg_tensor(g2)+theme_classic(base_size = 40) +theme(legend.text=element_text(size=30),legend.key.width =unit(3.5,"cm"),legend.title = element_text(size=30))+scale_fill_gradient2(low = "blue",high = "red",mid = "white",midpoint = 0,name=expression(paste('Extern. Effect (',Delta,R^2[adj],')')),guide = guide_colorbar(legend.position='top',title.position="top",ticks.colour = "gray50", ticks.linewidth = 7))+ggtitle("")+xlab("Functional Hierarchy")+ylab("Functional Hierarchy")+geom_vline(xintercept = mean(range(doubleBwAgeCorTMDifDf$net1tmvec)),linetype='dashed',size=1.5)+geom_hline(yintercept = mean(range(doubleBwAgeCorTMDifDf$net1tmvec)),linetype='dashed',size=1.5)+theme(legend.position='top')
```

```{r}
# Psychosis
ggplot(BwAgeCorTMDifDf,aes(x=tmdifvec,y=ageDR2vec_PS))+ geom_text(data=BwAgeCorTMDifDf,size=10,label="\u25D6",family="Arial Unicode MS",aes(x=tmdifvec,y=ageDR2vec_PS,color=Net1Vec))+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(data=BwAgeCorTMDifDf,aes(x=tmdifvec,y=ageDR2vec_PS,color=Net2Vec),size=10,label="\u25D7",family="Arial Unicode MS")+theme(legend.position = "none") + xlab('Transmodality Difference') + ylab(expression(paste('Psychosis Effect (',Delta,R^2[adj],')')))+theme_classic(base_size = 40)+theme(legend.position = "none")+geom_smooth(method='lm',color='black',size=2)

g2 <- gam(ageDR2vec_PS ~ te(net2tmvec,net1tmvec,k=4),data = doubleBwAgeCorTMDifDf)

gg_tensor(g2)+theme_classic(base_size = 40) +theme(legend.text=element_text(size=30),legend.key.width =unit(3.5,"cm"),legend.title = element_text(size=30))+scale_fill_gradient2(low = "blue",high = "red",mid = "white",midpoint = 0,name=expression(paste('Psychosis Effect (',Delta,R^2[adj],')')),guide = guide_colorbar(legend.position='top',title.position="top",ticks.colour = "gray50", ticks.linewidth = 7))+ggtitle("")+xlab("Functional Hierarchy")+ylab("Functional Hierarchy")+geom_vline(xintercept = mean(range(doubleBwAgeCorTMDifDf$net1tmvec)),linetype='dashed',size=1.5)+geom_hline(yintercept = mean(range(doubleBwAgeCorTMDifDf$net1tmvec)),linetype='dashed',size=1.5)+theme(legend.position='top')
```

```{r}
# Anxious Misery
ggplot(BwAgeCorTMDifDf,aes(x=tmdifvec,y=ageDR2vec_PS))+ geom_text(data=BwAgeCorTMDifDf,size=10,label="\u25D6",family="Arial Unicode MS",aes(x=tmdifvec,y=ageDR2vec_PS,color=Net1Vec))+scale_color_manual(values=ycolors,limits=Y7vec)+geom_text(data=BwAgeCorTMDifDf,aes(x=tmdifvec,y=ageDR2vec_PS,color=Net2Vec),size=10,label="\u25D7",family="Arial Unicode MS")+theme(legend.position = "none") + xlab('Transmodality Difference') + ylab(expression(paste('Psychosis Effect (',Delta,R^2[adj],')')))+theme_classic(base_size = 40)+theme(legend.position = "none")+geom_smooth(method='lm',color='black',size=2)

g2 <- gam(ageDR2vec_AM ~ te(net2tmvec,net1tmvec,k=4),data = doubleBwAgeCorTMDifDf)

gg_tensor(g2)+theme_classic(base_size = 40) +theme(legend.text=element_text(size=30),legend.key.width =unit(3.5,"cm"),legend.title = element_text(size=30))+scale_fill_gradient2(low = "blue",high = "red",mid = "white",midpoint = 0,name=expression(paste('Anx-Mis Effect (',Delta,R^2[adj],')')),guide = guide_colorbar(legend.position='top',title.position="top",ticks.colour = "gray50", ticks.linewidth = 7))+ggtitle("")+xlab("Functional Hierarchy")+ylab("Functional Hierarchy")+geom_vline(xintercept = mean(range(doubleBwAgeCorTMDifDf$net1tmvec)),linetype='dashed',size=1.5)+geom_hline(yintercept = mean(range(doubleBwAgeCorTMDifDf$net1tmvec)),linetype='dashed',size=1.5)+theme(legend.position='top')
```

```{r}
### does hierarchical devel. differ in psychopathological and norm. groups?

# split into thirds on overall psych
OV_thirds<-quantile(masterdf$overall_psychopathology_4factorv2,c(0:3/3))
lowOV<-masterdf[masterdf$overall_psychopathology_4factorv2<(OV_thirds[2]),]
lowOV_indices<-match(lowOV$bblid,masterdf$bblid)
highOV<-masterdf[masterdf$overall_psychopathology_4factorv2>(OV_thirds[3]),]
highOV_indices<-match(highOV$bblid,masterdf$bblid)
```

```{r}
# starting with low psychopathology
# calculate age effects for each network. This is the part where we loop over all networks ot get all our measures of interest, delta R^2 and associated stat. significance, the slope of estimated age effects across the age-range of our sample, etc.
# set covariates formula for iterating over in the loop
covariates=" ~s(Age,k=3)+Sex+Motion"

# functions - adapted

# difference in R2
DeltaR2EstVec<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(masterdf$Age[lowOV_indices]),as.numeric(masterdf$Sex[lowOV_indices]),masterdf$Motion[lowOV_indices],x))
  colnames(scaledf)<-c('Age','Sex','Motion','varofint')
  
  # no-age model (segreg ~ sex + motion)
  noAgeGam<-gam(varofint~Sex+Motion,data=scaledf)
  noAgeSum<-summary(noAgeGam)
  # age-included model for measuring difference
  AgeGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  AgeSum<-summary(AgeGam)
  
  dif<-AgeSum$r.sq-noAgeSum$r.sq
  
  # partial spearmans to extract age relation (for direction)
  pspear=pcor(scaledf,method='spearman')$estimate
  corest<-pspear[4]
  if(corest<0){
    dif=dif*-1
  }
  
  return(dif)
  
}

# Next, to derive the statistical significance of observed age effects, we need to test if the two models (one with an age term, one without) are significantly different. We use an ANOVA for this procedure. These p-values will eventually be FDR-corrected.

# chisq test sig. output
DeltaPEstVec<-function(x){
  
  # relevant df
  scaledf<-data.frame(cbind(as.numeric(masterdf$Age[lowOV_indices]),as.numeric(masterdf$Sex[lowOV_indices]),masterdf$Motion[lowOV_indices],x))
  colnames(scaledf)<-c('Age','Sex','Motion','varofint')
  
  # no-age model (segreg ~ sex + motion)
  noAgeGam<-gam(varofint~Sex+Motion,data=scaledf)
  # age-included model for measuring difference
  AgeGam<-gam(varofint~Sex+Motion+s(Age,k=3),data=scaledf)
  
  # test of dif with anova.gam
  anovaRes<-anova.gam(noAgeGam,AgeGam,test='Chisq')
  anovaP<-anovaRes$`Pr(>Chi)`
  anovaP2<-unlist(anovaP)
  return(anovaP2[2])
  
}
```

```{r}
# initialize output vectors
SplineP<-rep(0,length=length(lowOV[,indiv_nsegcols_ind]))
Avg_BW_Vector<-rep(0,length=length(lowOV[,indiv_nsegcols_ind]))
avg_bw_deltaR2<-rep(0,length=length(lowOV[,indiv_nsegcols_ind]))
avg_bw_deltaP<-rep(0,length=length(lowOV[,indiv_nsegcols_ind]))

# borrowing colnames from indiv_nsegcols to keep network/scale ordering/mappings
colnames(bwAvgCon)<-gsub("_seg_","_avgBw_",colnames(masterdf[,indiv_nsegcols_ind]))
bwAvgCondf<-data.frame(bwAvgCon[lowOV_indices,])

#add on covariate columns
bwAvgCondf$Age<-masterdf$Age[lowOV_indices]
bwAvgCondf$Sex<-masterdf$Sex[lowOV_indices]
bwAvgCondf$Motion<-masterdf$Motion[lowOV_indices]

#for i in 464, -3 because age sex motion columns sit at the end
for (i in 1:(length(bwAvgCondf)-3)){
  # borrowing colnames from indiv_nsegcols to keep network mappings
  x<-colnames(bwAvgCondf[i])
  avg_bw_deltaR2[i]<-DeltaR2EstVec(bwAvgCondf[i])
  avg_bw_deltaP[i]<-DeltaPEstVec(bwAvgCondf[i])
  form<-as.formula(paste("",x,"", covariates, sep=""))
  igam<-gam(formula = form,data=bwAvgCondf)
  SplineP[i]<-summary(igam)$s.pv
}

# fdr-correct spline P values for each network's estimated age effect
SplineP_fdr<-p.adjust(SplineP,method='fdr')

# network-level sig vector - this will be used for color contrast in plots (desaturating non-sig)
NL_sigVec<-logical(464)
NL_sigVec[SplineP_fdr<0.05]<-TRUE

# bring all of the filled-out veectors together into a dataframe for plotting
bwdf<-data.frame(tmvec,scalesvec,domnetvec,domnetvec17,netpropvec,avg_bw_deltaR2,avg_bw_deltaP)
```

```{r}
# Map nonsig to grey
bwdf$domnetvecSig<-'NonSig'
# sig where CL_vec indicates
bwdf$domnetvecSig[NL_sigVec]<-as.character(bwdf$domnetvec[NL_sigVec])
# order for plot legend
bwdf$domnetvecSig<-as.factor(bwdf$domnetvecSig)
bwdf$domnetvecSig<-factor(bwdf$domnetvecSig,levels=c("Motor","Visual","DA","VA","Limbic","FP","DM","NonSig"),labels=c("Motor","Visual","DA","VA","Limbic","FP","DM","NonSig."))

# stats for fig-lm
Age_net_lm<-lm(avg_bw_deltaR2~tmvec,data=bwdf)
cor.test(bwdf$tmvec,bwdf$avg_bw_deltaR2,method='spearman')

# Figure 3C
ggplot(bwdf,aes(tmvec,avg_bw_deltaR2)) + geom_point(size=6,alpha=.8,aes(color=domnetvecSig))+ scale_color_manual(values=c('#3281ab','#670068','#007500','#b61ad0','#b8cf86','#d77d00','#c1253c','gray80')) + xlab("Functional Hierarchy") + ylab(expression(paste('Age Effect (',Delta,R^2[adj],')',sep=''))) +theme_classic(base_size = 40) +guides(color=guide_legend(title="Yeo 7 Overlap"))+theme(plot.margin=margin(b=3,t=.1,l=.1,r=.1, unit='cm'), legend.position=c(.42,-.24),legend.direction = "horizontal",legend.title=element_text(size=30),legend.text=element_text(size=30))+geom_smooth(method='lm',color='black',size=3)
```

```